"""Named building blocks an activity configuration can pick from.

ENGINE INTERNALS. A configuration refers to these by NAME (display_fields / effects / flag_rules in
activities.py); it never contains code. If an activity needs something that is not in these three
registries, STOP and ask: do not edit this file to suit one activity.

    DISPLAY_FIELDS  extra lines on the operator's student card
    EFFECTS         work done inside the confirm transaction, before the event is written; may add
                    to the event's details
    FLAG_RULES      may add a flag (e.g. LATE) to the event
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Optional

from sqlalchemy import text

from backend.engine.queries import active_completion, clock_text


@dataclass(frozen=True)
class DisplayField:
    label: str
    provider: Callable  # (conn, student: dict, ctx: EngineContext) -> Optional[str]


# ------------------------------------------------------------------ display fields
def _prn(conn, student, ctx):
    return student["prn"]


def _programme(conn, student, ctx):
    return student["programme"]


def _school(conn, student, ctx):
    return student["school"]


def _queue_position(conn, student, ctx):
    """The position the student holds, or the one they will get when confirmed."""
    held = conn.execute(text("SELECT queue_position FROM queue WHERE student_id = :s"), {"s": student["id"]}).scalar()
    if held is not None:
        return f"Position {held}"
    upcoming = conn.execute(text("SELECT coalesce(max(queue_position), 0) + 1 FROM queue")).scalar_one()
    return f"Position {upcoming} (when confirmed)"


def _thobe_issued(conn, student, ctx):
    allocation = active_completion(conn, student["id"], "THOBE_ALLOCATION")
    if allocation is None:
        return "Not on record yet"  # may simply not have synced from the Stadium yet
    return f"Yes — issued {clock_text(allocation['server_time'], ctx.settings.event_utc_offset_minutes)}"


def _money_received(conn, student, ctx):
    received = active_completion(conn, student["id"], "MONEY_RECEIVED")
    if received is None:
        return "Not on record yet"
    return f"Yes — received {clock_text(received['server_time'], ctx.settings.event_utc_offset_minutes)}"


def _eligibility(conn, student, ctx):
    """Lunch needs the robe AND the money back (or an Admin waiver for either)."""
    def part(activity, thing, waived):
        done = active_completion(conn, student["id"], activity)
        if done is None:
            return f"{thing} return pending"
        if done["kind"] == "WAIVER":
            return waived
        return f"{thing} returned {clock_text(done['server_time'], ctx.settings.event_utc_offset_minutes)}"
    return " · ".join((part("THOBE_RETURN", "Robe", "Robe waived by Admin"),
                       part("MONEY_RETURNED", "Money", "Money kept by Admin")))


DISPLAY_FIELDS: dict[str, DisplayField] = {
    "prn": DisplayField("PRN", _prn),
    "programme": DisplayField("Programme", _programme),
    "school": DisplayField("School", _school),
    "queue_position": DisplayField("Queue position", _queue_position),
    "thobe_issued": DisplayField("Robe issued", _thobe_issued),
    "money_received": DisplayField("Money received", _money_received),
    "eligibility": DisplayField("Eligibility", _eligibility),
}


# ------------------------------------------------------------------ effects
def _enqueue(conn, student, ctx) -> dict:
    """Queue: take the next position from the shared counter, in the SAME transaction as the event
    (first come, first shown). The position is recorded on the event."""
    # The pipeline only reaches here when the student has NO active Queue completion. A queue row that is
    # still there therefore belongs to a completion an Admin reversed: drop it so the student is queued
    # again at the BACK (a new position), not blocked by the old row. (Concurrent confirms are still
    # settled by the unique index on the event, which rolls the loser's delete back too.)
    # Take this student's row lock FIRST, so concurrent confirms for the same student wait their turn here
    # instead of each grabbing the queue counter and the queue key in a different order and deadlocking
    # (seen as an occasional 503 when several desks confirmed one student at once). NO KEY UPDATE does not
    # block the foreign-key checks that other students' writes make.
    conn.execute(text("SELECT 1 FROM students WHERE id = :s FOR NO KEY UPDATE"), {"s": student["id"]})
    conn.execute(text("DELETE FROM queue WHERE student_id = :s"), {"s": student["id"]})
    position = conn.execute(
        text("INSERT INTO queue (student_id) VALUES (:s) RETURNING queue_position"), {"s": student["id"]}
    ).scalar_one()
    return {"queue_position": position}


EFFECTS: dict[str, Callable] = {"enqueue": _enqueue}  # (conn, student, ctx) -> dict merged into details


# ------------------------------------------------------------------ flag rules
def _late_registration(conn, student, ctx) -> Optional[str]:
    """Reporting after the cutoff is accepted and flagged LATE (TODO Phase 7 assumption)."""
    late = conn.execute(text("SELECT late_cutoff IS NOT NULL AND now() > late_cutoff FROM settings")).scalar()
    return "LATE" if late else None


FLAG_RULES: dict[str, Callable] = {"late_registration": _late_registration}  # (conn, student, ctx) -> flag | None
